name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract release notes from CHANGELOG.md
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          echo "Tag: ${TAG_NAME}"
          TAG_NO_V="${TAG_NAME#v}"
          echo "Version (no v): ${TAG_NO_V}"

          # Extract section starting at heading matching the version (without leading 'v')
          awk -v tag="$TAG_NO_V" '
            BEGIN { f=0 }
            $0 ~ "^##[[:space:]]*" tag "([[:space:]]|$)" { f=1; print; next }
            # next heading that looks like another version ends the section
            /^##[[:space:]]*[0-9]+\.[0-9]+\.[0-9]+/ { if (f==1) exit }
            { if (f==1) print }
          ' CHANGELOG.md > RELEASE_NOTES.md || true

          if [ ! -s RELEASE_NOTES.md ]; then
            echo "Could not find release notes for ${TAG_NO_V} in CHANGELOG.md; using fallback." >&2
            echo "# ${TAG_NAME}" > RELEASE_NOTES.md
            echo >> RELEASE_NOTES.md
            head -n 100 CHANGELOG.md >> RELEASE_NOTES.md
          fi

          echo "--- RELEASE NOTES ---"
          cat RELEASE_NOTES.md
          echo "---------------------"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
