name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 5.2.0)'
        required: true
      body_file:
        description: 'Optional path to release notes file (relative to repo root)'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update manifest.json version
        run: |
          set -euo pipefail
          v="${{ github.event.inputs.version }}"
          echo "Setting manifest version to $v"
          jq --arg v "$v" '.version=$v' helios_pro_ventilation/manifest.json > manifest.tmp && mv manifest.tmp helios_pro_ventilation/manifest.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helios_pro_ventilation/manifest.json
          git commit -m "chore: bump version to $v [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push || true

      - name: Create tag
        run: |
          v="${{ github.event.inputs.version }}"
          git tag -a "v${v}" -m "Release v${v}" || echo "Tag already exists"
          git push origin "v${v}" || echo "Tag push skipped"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          bodyFile: ${{ github.event.inputs.body_file }}
          draft: false
          prerelease: false
name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract release notes from CHANGELOG.md
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          echo "Tag: ${TAG_NAME}"
          TAG_NO_V="${TAG_NAME#v}"
          echo "Version (no v): ${TAG_NO_V}"

          # Extract section starting at heading matching the version (without leading 'v')
          awk -v tag="$TAG_NO_V" '
            BEGIN { f=0 }
            $0 ~ "^##[[:space:]]*" tag "([[:space:]]|$)" { f=1; print; next }
            # next heading that looks like another version ends the section
            /^##[[:space:]]*[0-9]+\.[0-9]+\.[0-9]+/ { if (f==1) exit }
            { if (f==1) print }
          ' CHANGELOG.md > RELEASE_NOTES.md || true

          if [ ! -s RELEASE_NOTES.md ]; then
            echo "Could not find release notes for ${TAG_NO_V} in CHANGELOG.md; using fallback." >&2
            echo "# ${TAG_NAME}" > RELEASE_NOTES.md
            echo >> RELEASE_NOTES.md
            head -n 100 CHANGELOG.md >> RELEASE_NOTES.md
          fi

          echo "--- RELEASE NOTES ---"
          cat RELEASE_NOTES.md
          echo "---------------------"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
